https:
  port: "8081"
  host: "localhost"
  basepath: "/"
  keystore: 
    path: "keystore/keystore-local.jks"
    password: "![NZVjUKeZNLI=]"
    type: "JKS"


process: 
  host: "localhost"
  port: "8082"  
  basepath: "/api"
  client_id: "9353b6fed7c04b39866f4379a310351d"
  client_secret: "![eUi3ibPmLJD20uqNHSGJ4W8uczEGQJIcz+4UPnYYqlPxnH9v20++EQ==]"
  protocol: "HTTPS"
  keystore: 
    path: "keystore/truststore-local.jks"
    password: "![NZVjUKeZNLI=]"
    type: "JKS"
    
api: 
  id: "19441845"
